apiVersion: v2
name: livepeer-gateway
description: Livepeer gateway chart supporting singleton and distributed modes
type: application
keywords:
  - livepeer
  - livepeer-gateway
  - helm
  - kubernetes
home: https://charts.livepeer.org/
sources:
  - https://github.com/livepeer/livepeer-charts
  - https://github.com/livepeer/livepeer-charts/blob/main/charts/livepeer-gateway/README.md
version: 1.0.0
appVersion: "v0.8.9"
icon: https://cdn.prod.website-files.com/660e2fe4cba2fca14e90fc61/6644be2f885be8fd1dc92233_favicon256-t.png
dependencies:
  - name: livepeer-common
    version: 1.0.0
    repository: file://../livepeer-common
maintainers:
  - name: Livepeer
    email: support@livepeer.org
    url: https://github.com/livepeer
  - name: hjpotter92
    url: https://github.com/hjpotter92
